### ISSUE TITLE
App not reading Heart Rate

### ISSUE THREAD

**Issue by dariomarciano** [tijmenvangulik/Ergometerspace#1]
Tried both the Android app (Bluetooth connection) and the web page via Windows data server app, they get all the data but not heart rate (tried both the plugin I'm working on and the example heart rate plugin).
Working on a concept 2 model c with pm5

**Comment by tijmenvangulik** [comment]
It worked before on my pm5, I have the same configuration, maybe something is broken since the last changes. I check it out.

**Comment by tijmenvangulik** [comment]
The problem could be at two places. (sometimes the hearth beat connections gets lost when you connect an device) A questions to figure out what went wrong:
-  Did the PM5 display the heart while the app did not show the heart rate?

**Comment by dariomarciano** [comment]
The pm5 display showed it, the app didn't. strokedata.heartrate was 0.
Testing again later on

**Comment by tijmenvangulik** [comment]
I have tested it this evening. But the heart beat worked fine. (I tested both an ant and a blue tooth connection) I need some more info:
- What firmware version do you use? (maybe you need an upgrade)
- Does the history widget show the heart rate? (this way I tested it)
- Did you install the latest version (current is 2.0.11 which I posted today)

**Comment by tijmenvangulik** [comment]
Another thing: Correct me if I am wrong you have written an widget which can notify you when certain values are too low or to high. (for a certain distance) Have you taken a look at the Notifications widget. This one can also do this. If so , I am interested why this widget did not work for you and if I can improve it.

**Comment by tijmenvangulik** [comment]
I have not heart of you for some time, I need some more info to repeat it. I close the issue now.
