### ISSUE TITLE
Is it possible to set up data server?

### ISSUE THREAD

**Issue by justinriddiough** [tijmenvangulik/Ergometerspace#14]
I have a number of raspberry devices here that I could connect to create a data server that would be consumed by my gaming pc with the vr headset. It might be awhile before I am able to get my hands on a pm5 monitor. 

If there were a linux / ubuntu / debian way to get the data, that would be excellent.

**Comment by tijmenvangulik** [comment]
That should be possible. May be you can also run chrome on a raspberry pi (never tested it). Or you can just connect using an usb and use a long cable.

https://www.linux.com/training-tutorials/run-google-chrome-raspberry-pi/ <https://www.linux.com/training-tutorials/run-google-chrome-raspberry-pi/>

**Comment by justinriddiough** [comment]
I do have some long usb cables I can test with. I'll give it a try real quick with the windows client to see if I can get it going

**Comment by justinriddiough** [comment]
So the experience was after installing the software, it detected and read the data with no problem. I was wearing the VR helmet, but it was treated as a desktop app - I could see it through a virtual desktop, and click the vr goggles, but it just showed the left and right eye on a virtual flat screen

**Comment by tijmenvangulik** [comment]
Maybe you have to use another browser. Check if you vr system has a custom browser which support 3d (it should be chromium based browser )

**Comment by justinriddiough** [comment]
Let me try that. I might have disabled the browser VR before because my tracking stations would randomly turn on when visiting some websites.

**Comment by tijmenvangulik** [comment]
The browser must support webvr. I do not yet support WebXR. And the browser must be chromium based for the USB/ blue tooth connections.

Tijmen

**Comment by justinriddiough** [comment]
I turned on webvr in chrome, the Index doesn't seem to catch on. Should it toggle when I click the goggle icon? When does the vr mode kick into headsets for other devices?

**Comment by justinriddiough** [comment]
I think unfortunately the valve index doesn't support webvr, not sure about webXR. Have you considered putting it in a game 3d engine like Unity?

**Comment by tijmenvangulik** [comment]
I am a single developer and it is written in my spare time so I can not support all platforms. I depend on VR vendors implementing the official standards. If they do not do this it will not run on specific devices. My bet is that the big vr vendors will support the official web standards on the long run. So I am only focussing on making the app work on the web vr standards.

Tijmen

**Comment by justinriddiough** [comment]
That makes sense. I like what you've got so far and hope to explore what you've created. I agree in time there will be support for webvr / webxr eventually on the index.
