### ISSUE TITLE
Feature request: support for heartrate monitor strap

### ISSUE THREAD

**Issue by justinriddiough** [tijmenvangulik/Ergometerspace#16]
Would it be possible to add support for heart-rate monitor as separate bluetooth device? I think there are libraries out there and the implementation is mostly standard..

**Comment by tijmenvangulik** [comment]
Thank you for your input. That would be a nice feature for the users which do not have an PM5. (If you have a PM5 you connect the heart rate to the monitor and then ergometer-space will show the heart rate)

**Comment by tijmenvangulik** [comment]
In version 3.3.0 you can directly connect to a blue tooth heart rate monitor.

**Comment by justinriddiough** [comment]
how exciting, can't wait to try this out! thanks for looking into it!

**Comment by tijmenvangulik** [comment]
Please let me know if you have any problems.

Tijmen

**Comment by tijmenvangulik** [comment]
I have added two new heart rate widgets in the last release (3.4.0) which may interest you.
