### ISSUE TITLE
Displaying past workouts in widgets seems very touchy

### ISSUE THREAD

**Issue by justinriddiough** [tijmenvangulik/Ergometerspace#17]
Loading some of the past workouts, it seems some of them don't save in a way that is processed well.

The Strokes p/m will usually update properly, but the 'power curve history' widget and split time widget  sometimes don't load data at all. 

Some can take a couple minutes to load & process.

The csvs from export look a little odd too.. anything I can do to troubleshoot this further? As far as I can recall, if I look at the screen after the workout, everything looks right. It's only going back later that I see the issue.
[Workout202042862453.csv.txt](https://github.com/tijmenvangulik/Ergometerspace/files/4546033/Workout202042862453.csv.txt)
[Workout202042862355.csv.txt](https://github.com/tijmenvangulik/Ergometerspace/files/4546034/Workout202042862355.csv.txt)

**Comment by tijmenvangulik** [comment]
Thank you for your input. It is possible that older activities do not have a power curve included because the power curve feature was  added recently and in older version it did not add the power curve. It looks like it concatenated multipe powercurves in one curve (it could not detect the end of a curve so it sees multipe curves as one) Some questions to help me pin point where it goes wrong:
- Version of the app?
- Platform : Web/Desktop app/Android?
- Connection Usb/BlueTooth/Dataserver?
- Device: PM3 4 or 5


Tijmen

**Comment by justinriddiough** [comment]
Hmm. These were all within a couple days of each other.

- Version:  3.0.6 or so? One or two versions back, around 4/20
- Platform: Desktop app
- Connection: USB
- Device PM3

[Workout2020428104923.csv.txt](https://github.com/tijmenvangulik/Ergometerspace/files/4547600/Workout2020428104923.csv.txt)

Another row on the same day - it seemed to record correctly.

**Comment by tijmenvangulik** [comment]
Thanks, I connect my PM3 to the ergometer and see if I can repeat the problem.

Tijmen

**Comment by justinriddiough** [comment]
I wonder if it could be a firmware thing. 

What I did (without closing app in between sessions):

Have it set to 250m, row 
Come back later, go to "rerow", row again
Come back later, go to "rerow", row again

**Comment by tijmenvangulik** [comment]
I tried to reproduce the problem using my PM3. But all worked fine. Some more questions
- What is the Firmware version, you can find it in More options-> Utilities-> Product Id
- Are you using an mac or PC, and what OS version

**Comment by tijmenvangulik** [comment]
Please do not directly I upgrade your ergometer. First  I would like to know the version number. because if an upgrade fixes the problem, with this info I could make a warning message.

Tijmen

**Comment by tijmenvangulik** [comment]
If the firmware upgrade did not fix it. Please report the hardware version which is in the same screen as the firmware version

**Comment by justinriddiough** [comment]
Firmware version 315
Hardware version 321

**Comment by tijmenvangulik** [comment]
Ok that is exactly the same version as my PM3.

**Comment by justinriddiough** [comment]
Hmm, and you didn't touch anything on the app between the rows? I wonder if it maybe is something with the USB connection or otherwise. It recorded things like total time, distance, but stroke data got garbled. I'll try testing again in the next day or two a few trials to see how it goes.

**Comment by tijmenvangulik** [comment]
Do you have a mac or a PC? I test on a mac. Which os version?
I will do a 250 run instead of 100. maybe there is a difference? It looks as if the communication is very slow, so slow that it can not fetch the curve during the recover and then it does not know when the curve ends and it concatenates the curve.

Tijmen

**Comment by tijmenvangulik** [comment]
I have seen before that an PM3 can get confused.(rare case) Resetting by pulling out the batteries and put it back in again helps.

**Comment by tijmenvangulik** [comment]
I just tested 250 meters 2 times, with different pace/ power. All worked. So it looks like the traing length does not mater.

Tijmen

**Comment by justinriddiough** [comment]
I will test some more later this evening. I had opened the app, and let it run all day, while doing a 250 every hour or so to see if it would log each time I rowed automatically as a separate workout.
I am on PC. 

I will also try with the most recent version.

**Comment by tijmenvangulik** [comment]
Ok I will also do a test on a PC, maybe there is a difference

**Comment by tijmenvangulik** [comment]
I did now 3 runs on a PC. But I all went well. So The problems may be on some other level. 
- My Mac/PC has an USB 3 port. (What kind of port do you have)
- Is there some thing wrong with the cable? 
- Try to reset the pm3 (get out the batteries and put it back in)
- I have windows 10 Home 64 bits 17134.950 (what is your version)

Tijmen

**Comment by justinriddiough** [comment]
- Port is USB 3, cable is a 25 foot USB 3 extension cable with a USB to square usb plugged into it
- It is a possibility with considering (signal loss possibly?), though I haven't had other issues (I might try connecting a webcam and see if there are any issues there)
- Will try battery reset after a few tests today
- Windows 10 Home 64 bits 18363.778

I will try a few more rows and see if I am still having issues. I did the first one and it logged correct, but I closed and reopened the app after so it's not quite the same as when I left it opened.

**Comment by tijmenvangulik** [comment]
25 foot cable is very long. I have tested it with a short cable (2 foot) It looks like this is above the official specs:

https://www.techwalla.com/articles/what-is-the-maximum-length-of-a-usb-cable

Tijmen

**Comment by justinriddiough** [comment]
Sorry, it is 15 feet. https://www.amazon.com/gp/product/B06XFWYWFF/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1

**Comment by justinriddiough** [comment]
I still think it could be a cable issue. I think its okay to close this for now, and I'm going to try to take another approach - to see if I can run it through the browser on a raspberry device that I might mount to the rower itself.

**Comment by tijmenvangulik** [comment]
Thank you for reporting this. I have seen the same problem before with one other user. So I want to fix this problem. If you are a developer ,I could provide a  version with the debugger enabled to check on errors. You can always contact me again.

Tijmen
