### ISSUE TITLE
Feature request: App auto-update

### ISSUE THREAD

**Issue by neural-loop** [tijmenvangulik/Ergometerspace#18]
Would be nice to have a method to automatically update the desktop app from within the app when a new version is released. Currently involves seeing the notification, browsing to the website -> finding the link -> downloading and installing new version

**Comment by tijmenvangulik** [comment]
Good idea

**Comment by tijmenvangulik** [comment]
One small step further. In the message there is a link which goes to the download page.

**Comment by justinriddiough** [comment]
That's great, that will make it easier.

**Comment by tijmenvangulik** [comment]
The native app has been removed because it is not needed any more. You can install the app as progresive web app (just go to the website and install the app from the search bar, you will get automatic updates)
