### ISSUE TITLE
Plugin Request: Metronome

### ISSUE THREAD

**Issue by neural-loop** [tijmenvangulik/Ergometerspace#19]
I may try to create a plugin myself, wondered if there was any input. 

When I try to use the 'stroke advisor' and it's telling me 'more x / y / z' trying to focus on those things on the fly as well as keeping rhythm is challenging. 

When I turned on a metronome, I was able to adjust to the advisor and get smoother curves without speeding up or slowing down between strokes. 

For me, the goal is to dial in a pace that allows me to maintain a steady heart rate (within a given range) for longer endurance rows. Would also like to track and record the difference in VO2max over time (a little out of scope for a metronome, but part of the overall use)

Some research:
https://www.quora.com/How-do-you-set-up-a-metronome-to-train-a-2-1-rowing-ratio
https://apps.apple.com/us/app/metrownome-a-rowing-metronome/id561712660

**Comment by tijmenvangulik** [comment]
Hi,

Nice Idea. The stroke advisor uses only the power curve as input for giving an advice. It mainly focuses on how you have spreader the power in your stroke. The power curve can not be used for a metro nome function (it is too slow and it comes too late ) The stroke events (Phase) event and the Strokes per minute events are a better indication for knowing when the stroke starts and when it ends. 

there is some info on how to write plugins
https://github.com/tijmenvangulik/Ergometerspace/blob/master/PLUGINS.md

you will need the following events
subNewStrokePhase
subStrokeDataUpdate

success

Tijmen

**Comment by tijmenvangulik** [comment]
I am now working on calculating the recover/total stroke time ratio. It looks like that it is a challenge to get the correct values. But I think it is a good feature because this ratio helped me row better on the water (in a skiff). I hope this will have the same effect as your metronome.

**Comment by justinriddiough** [comment]
Very interesting. When I set up the metronome, I was just doing every half tic of the metronome, I tried going into some kind of drum machine and setting up a rhytm that would do 2:1 but didn't get it dialed in. 

When doing the 1:1 ratio, sometimes I would sit at the end of the catch for just a moment until the next beat started. That sounds interesting having a ratio on there.

**Comment by tijmenvangulik** [comment]
The latest version 5.6.0 has a metronome widget. It may be a bit long a go , but you can test it if you want and send some feedback.
