### ISSUE TITLE
App not releasing plugin id on plugin delete

### ISSUE THREAD

**Issue by dariomarciano** [tijmenvangulik/Ergometerspace#2]
When I add a plugin from file, delete it, then add it again the app won't let me, throwing an "Application plugin with same id <id> already exists" error

**Comment by tijmenvangulik** [comment]
Thank you for reporting, I will work on this..

**Comment by tijmenvangulik** [comment]
I could not yet repeat your issue. Dit you get an error while installing the plugin? (check the console) When the plugin is not correctly initialized the uninstall may go wrong.  It may have to do with the mobile apps which still run the old version and the web which is already upgraded to the new typescript. And I assume that you edit it the web edition. As temporary work around , just kill the app and start it again. I will update the android app as soon as possible.

**Comment by dariomarciano** [comment]
Here's what I do:
start the app (or open the web page, it's the same)
click menu -> plugins; it lists no plugin
click add from file
Nothing loads, then I get an "ApplicationPlugin with same id dariomarciano.ergWorkout already exists".
Attached you'll find the plugin, ofc delete the .txt extension, had to add it coz of github.

[ergWorkout.JSON.txt](https://github.com/tijmenvangulik/Ergometerspace/files/1716731/ergWorkout.JSON.txt)

**Comment by tijmenvangulik** [comment]
I can repeat your issue. I have fixed it in my code. I will look this evening at the heart rate problem, Hopefully I can fix them both before I post an update

**Comment by tijmenvangulik** [comment]
I fixed this issue and rolled out an new release. (the fixed is in 2.011) I have added another feature which can be helpful when writing plugs: When you save the plugin code it will now automatically reload the widget which where controlled by the plugin. This saves some time when debugging.
