### ISSUE TITLE
PM3 connection with cable doesn't seem to work

### ISSUE THREAD

**Issue by JAQuent** [tijmenvangulik/Ergometerspace#22]
Hey,
I downloaded the latest Windows version of Ergometerspace. It does seem to recognise that a rowing machine is connected but nothing is displayed (e.g. no split). That connection is there is clear because it doesn't ask me to connect machine and the workout type change when I set it on the PM3 itself. 

Also, for other programs like RowPro or connect2 ulitily the connection works. 

I am running the whole thing with Windows 10 computer, the newest PM3 Firmware (332) and Hwardware version (340).

Do you need more information? Is there any diagonistic that I can run? I know a bit JS so curious to help.

**Comment by tijmenvangulik** [comment]
Thank you for your report. The windows version should directly connect to your PM3 device without asking when you have selected the usb connection type. I will check out the windows version and the new firm ware (I have got 315). The only thing you can do now is to reset the PM3 device (take de batteries out and put it back in)

Tijmen

**Comment by tijmenvangulik** [comment]
I just found out what is wrong. The last heart rate belt feature has broken the electron app. I will fix this as soon as possible.

Tijmen

**Comment by tijmenvangulik** [comment]
The problem should now be fixed in 3.4.1

**Comment by tijmenvangulik** [comment]
I close this issue for now. If you have any problems with the fix, drop a mail or open an issue
