### ISSUE TITLE
Cant make a USB connection since I updated PM5 to 169

### ISSUE THREAD

**Issue by RoWLee10** [tijmenvangulik/Ergometerspace#23]
The new version of the Concept2 Utility installs an new device driver on windows and updates the PM5 to version 169.
Since doing that I can no longer connect to Ergometer space via the USB.   I have tried on two different computers, on with the Concept2 Utility and device driver updated and one without the update.   The USB connection fails on both, leading to the conclusion that it is version 169 in the PM5 that is causing the problem.

**Comment by tijmenvangulik** [comment]
Thank you for your report. I will look into this problem when I find some time..

Tijmen

**Comment by tijmenvangulik** [comment]
I have just updated my Pm5 to the september update and it still connects. There is however a difference, for my older pm5 hardware the september update is version 31. (you seem to have hardware version 900 )
https://www.concept2.com/service/monitors/pm5/firmware/timeline

Still having these problems?
