### ISSUE TITLE
How to upload results to my logbook

### ISSUE THREAD

**Issue by nickwales** [tijmenvangulik/Ergometerspace#26]
Hi, just checking if it's possible to upload results to my Concept2 logbook from the output you provide.

Thank you!

**Comment by tijmenvangulik** [comment]
Good question. This feature is on my wish-list. What you can do currently do is to make use of the concept2 features. Your training is stored on the concept2 device and in ergometer-space. You can upload your data to concept2 log book using the concept2 erg data app.

Tijmen

**Comment by tijmenvangulik** [comment]
I have just uploaded version 3.9.2 with this new feature. (for now web only, not the apps, if you have a android phone you need to run the web version which also can be installed)

* 3.9.2 (web only)
  - Allow upload to concept2 log (select a work out log and click on send to concept2) (only upload time, distance, timestamp and weight class, no verification codes yet)

**Comment by tijmenvangulik** [comment]
feature in 3.9.2

**Comment by nickwales** [comment]
Amazing, thank you!
