### ISSUE TITLE
PM4 fw 332 Android 12 connection

### ISSUE THREAD

**Issue by jr111** [tijmenvangulik/Ergometerspace#27]
Hello, followed the project off and on for a long time. Have used it previously on PC. The app will find the rower in the dropdown list. but the connect message never disappears and no data is transferred. I will sporadically get a user permission error about accessing the device. This hardware should have success? Thank you.

Edit to add it does connect and work properly with Ergdata for PM3 PM4

**Comment by tijmenvangulik** [comment]
Thank you for reporting this. It seems that android has some usb  security changes. I will look into this issue. It may take a while to fix it because I have some hardware issues with my current android phone. For now using a PC or upgrade your device to a PM5 is the only workaround.

Tijmen

**Comment by jr111** [comment]
The Nearby Devices permission present in Ergdata and Painsled is absent, it is not requested. I will try a couple of things. Thanks for your work it's a great project.

**Comment by tijmenvangulik** [comment]
I have found a problem of a missing USB configuration which may fix this. This fix is in  4.6.0 which should be in the play store now or the next view hours. I have not been able to test it on a new android version because my own phone is too old for the latest android. I hope that I can test it next week. But when you if you have time to check the USB feature I would  be grateful.

**Comment by jr111** [comment]
I appreciate the support of the older devices I look forward to test it on a PM3 as well, it has not updated in the store yet for me.

**Comment by tijmenvangulik** [comment]
I could reproduce your problem with a new phone. I have made a fix for it. I have just released this fix in version 4.7.0 which should be in the play store now or the next view hours. I have tested it with a PM5 and PM3 and a new android version.

**Comment by jr111** [comment]
Just had a test all is working. Thank you!
