### ISSUE TITLE
Power curve average 

### ISSUE THREAD

**Issue by Harry1997mcg** [tijmenvangulik/Ergometerspace#28]
I was wondering if there was a way of showing or introducing an average power curve for each workout. I think mine shows every single power curve or the last one but I think an average power curve would really help with the data and technical aspect of the app.

I think this is really revolutionary for me as my club have started using telemetry data on the water and being able to see an example curve live whilst rowing is a huge step forward to implement tecnical changes on the ergo.

**Comment by tijmenvangulik** [comment]
Thank you for the good idea. I have also thought about this. Calculating the average curve is easy. The only problem is that some times the algorithm cannot find the start of the curve and there are one or two curves which look wrong. This will mess up the average. I have to fix this last problem first. I will give this feature more priority.

Tijmen

**Comment by tijmenvangulik** [comment]
In the next release I will add support for the average power curve in the workout.

**Comment by tijmenvangulik** [comment]
I have published 5.4.0 with the average power curve feature. Web is available now. It may take a while before the mobile apps are available.

**Comment by tijmenvangulik** [comment]
Still not entirely happy with the result. The clean up routine does not always work correctly. Next release I will post a better average curve.

**Comment by tijmenvangulik** [comment]
The update 5.4.1 has a better average curve and adds a button to show the curve in the power curve widget
