### ISSUE TITLE
Cannot upload to c2 logbook if distance not an integer

### ISSUE THREAD

**Issue by fish2eggs** [tijmenvangulik/Ergometerspace#30]
Did a 30:00 minute row, for 5243.4m. Attempted to upload to c2 logbook, message was:

Workout: 16/04/2024, 8:13:05 pm: Could not create new result.: 
distance: Please enter the distance as just a number

When I manually entered the workout to c2 logbook, using "Add Workout" with the decimal part of the distance, got the message "Please make sure you only enter numbers here.'.  So it appears c2 only accepts integer distance.

**Comment by tijmenvangulik** [comment]
Thank you for reporting this. Was it a ''Just Row' activity? In that case I can imagine what went wrong. When this was not the case can you please export the workout and send it to me by mail: tijmen@vangulik.org.  A normal export will do (the first export in the menu) This way I hope I can quickly fix your problem.

**Comment by tijmenvangulik** [comment]
It was just what I thought so I can repeat the issue. I have made a fix. It will be in the next release. Thank you for bringing this up.

**Comment by fish2eggs** [comment]
Greetings,
the row in question was a "New workout", "Single Time", 0:30:00. (With a
pace boat, if that is relevant).  Entered directly through the PM5.

Log export attached.

Nigel

-- 
Nigel Rowe

**Comment by tijmenvangulik** [comment]
There is a new version 5.9.0 which fixes this issue. (It is directly available on the web but it may take some time before it is in the app store.) I close this issue. feel free to give more feedback/bug reports of feature requests..
