### ISSUE TITLE
Sourcecode

### ISSUE THREAD

**Issue by skraburski** [tijmenvangulik/Ergometerspace#4]
Hi,
Can you share sourcecode for connection with PM5 or technical documentation of connection?

Regards

**Comment by justinclift** [comment]
Interestingly, I was looking into PM4/5 dev stuff a few years ago too.

There's an official SDK:

&nbsp; &nbsp; https://www.concept2.com/service/software/software-development-kit

Their forum also has an area for SDK questions:

https://www.c2forum.com/viewforum.php?f=15

From memory, there's also an official wiki around somewhere though I don't remember the address off hand.  I found the wiki last time by looking through older forum posts.  There was definitely useful info on the wiki, and some example data files that can be used for various purposes.

**Comment by justinclift** [comment]
This looks potentially useful as well:

&nbsp; &nbsp; http://raspirowing.com

**Comment by tijmenvangulik** [comment]
The source code to connect to the device is published is the ergometerjs repository:
  https://github.com/tijmenvangulik/ErgometerJS
This repository is just for the documentation and the plugins of ergometer-space.
