### ISSUE TITLE
Crew Racing

### ISSUE THREAD

**Issue by AHerrod** [tijmenvangulik/Ergometerspace#6]
Hi Tijmen,

I'd been looking in to writing my own software (given my club/country all now confined indoors) until I found you'd done pretty much exactly what I was looking to do (and I'd be starting from nothing...)!

Regarding online crews: I was considering a system as follows:
>Rowers can create/invite others to crews, with stats for each crew (avg crew split time for various distances...)
>The split time of the crew is the average of everyone in the crew (maybe with weight adjustements... possibly....)
>Rowing out of time (or just with different rates) worsens the crew split time somehow
>The crew members row as long as it takes to complete their distance as a crew (using the crew average split), so that we don't have people in the same crew rowing for different lengths of time!

If you fancy help with implementing the above, I could spare some hours through the coming weeks!

Again: It's great to see this! Well done and thanks for your work! :)

**Comment by tijmenvangulik** [comment]
Hi 

Thank you for asking. I have also been playing with the same idea. I basically came up with a similar solution. This is on my wish list. You could even combine it with the shared power curve (already a current feature) You can get and additional speed boost when the power curve matches. It could be written in a separate widget , but it would be more convenient if it integrates into the existing widgets. You could start writing you own widget in a plugin, but on the long run I am going to write my own implementation. I am not yet starting on this feature. First I am going to focus on pear to pear data (the audio is already move to pear to pear ) This should reduce the latency and improve the row together experience. If you have any questions you can also contact on my email adres (you can find it in the app in the about box)

Tijmen

**Comment by AHerrod** [comment]
Sounds good! :)

**Comment by tijmenvangulik** [comment]
I have now added a feature which allows you to row in teams and you also have the observer role. This is ideal for rowing an regatta

**Comment by AHerrod** [comment]
Hi again Tijmen,

I just tested this with a fellow rower -- it seems work work, but the app crashed on my phone when we crossed the finish line (this isn't too big a problem -- I'll just use my laptop next time!)

Is the power-curve matching implemented?

Also, might you happen to be based at the Utrecht rowing centre? I ask because I was there last August picking up some stuff from EURow (was planning to do the same again this August). It's a fantastic location!

Cheers,
Alex

________________________________

**Comment by tijmenvangulik** [comment]
Hi Alex,

Thank you for the info. Yes in Utrecht, the room names gave it away I suppose :-) I check the android log if I can see a crash error. Currently I am working on making the peer to peer connections in the new team rooms more robust. Power curve matching is implemented, you can share a power curve with another rower and the widget will compare the curve. (I have added one small limit that teams can not look at each other power curves)

Tijmen

**Comment by AHerrod** [comment]
Is it possible to show the power curves to only those in the same crew? Then they can all try to match ;)

________________________________

**Comment by tijmenvangulik** [comment]
For now you can show only one curve of a rower of your team. The team captain should be the stroke. (you should match the curve of the stroke) In the future I will give the team a boost if all the rowers have a power curve which matches the curve of the stroke. 

Tijmen

**Comment by AHerrod** [comment]
Ahh okay. Makes sense! :)

-Alex

________________________________
