### ISSUE TITLE
Feature: Register 'Just row' workouts

### ISSUE THREAD

**Issue by fidel-perez** [tijmenvangulik/Ergometerspace#7]
It would be great if the app would register also the information for the 'just row' workouts for those days in which you are not sure how long (or the distance) you will be rowing and would like to keep it tracked.

**Comment by tijmenvangulik** [comment]
Yes, would be a good feature. This can be on the list

**Comment by tijmenvangulik** [comment]
I have added this feature in 4.6.0 
 Log just row in workout log when switched on in the setting
